void interrupt00h(void);
void interrupt04h(void);
void interrupt06h(void);
void interrupt08h(void);
void interrupt0ch(void);
void interrupt0dh(void);
void interrupt0eh(void);
void interrupt20h(void);
void interrupt21h(void);

void asm_interrupt00h(void);
void asm_interrupt04h(void);
void asm_interrupt06h(void);
void asm_interrupt08h(void);
void asm_interrupt0ch(void);
void asm_interrupt0dh(void);
void asm_interrupt0eh(void);
void asm_interrupt20h(void);
void asm_interrupt21h(void);
