include kernel/fs/Makefile

kernel_objs += kernel/init.o kernel/init_proc.o kernel/fifo.o kernel/memory.o\
kernel/types.o kernel/timer.o kernel/time.o kernel/task.o kernel/schedule.o\
kernel/pipe.o kernel/string.o kernel/string_format.o kernel/random.o kernel/sysinfo.o\
kernel/user.o kernel/page.o